server:
      port: 8888
#      client-auth: need  
logging:
  level:
    root: INFO         
    org:
      springframework:
        security: INFO 
        web: INFO
javax:
   net:
      ssl:
         trustStore: classpath:MyPublicKey.store
         trustStorePassword: tstapppass        